server:
  port: 9015
  error:
    include-stacktrace: never

spring:
  application:
    name: ms-usuarios
  kafka:
    bootstrap-servers: kafka-broker:29092

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-rdbms:5432/usuarios
    username: postgres
    password: 123

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"