server:
  port: 9015
  error:
    include-stacktrace: never

spring:
  application:
    name: ms-usuarios

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/usuarios
    username: postgres
    password: Caraluna.351

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"