server:
  port: 9004
  error:
    include-stacktrace: never

spring:
  application:
    name: ms-suscripciones

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-rdbms:5432/suscripciones
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  kafka:
    bootstrap-servers: kafka-broker:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ms-suscripciones
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"