version: '3.8'

services:
  bd-pagos:
    image: postgres:15
    container_name: postgres-pagos
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=pagos
    ports:
      - "5433:5432"