server:
  port: 9014
  error:
    include-stacktrace: never

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ms-promociones

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:postgres-rdbms}:${DB_PORT:5432}/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-broker:29092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: ms-promociones
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: cl.teatromoro.common.event

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}

  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 60