server:
  port: 9006
  error:
    include-stacktrace: never

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ms-funciones
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-rdbms:5432/funciones
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka-broker:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ms-funciones
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: cl.teatromoro.common.event

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 60

logging:
  file:
    name: logs/ms-funciones.log
  level:
    cl.teatromoro.funciones.client: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: FULL

jwt:
  secret: VGVhdHJvTW9yb0pXVFNlY3JldEtleTIwMjZTdXBlclNlZ3VyYQ==
  expiration-ms: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html